### PR TITLE
Initial prototype

### PR DESCRIPTION
**Pull request by jeromekelleher**
Pinging @tskit-dev/all for feedback here.

This is an initial prototype for a gzip-like ``tscompress`` CLI (and Python API). Usage:
```
$ msp simulate 1000 -r 10 -u 10 msprime.trees
$ cp msprime.trees msprime.trees.original
$ python3 -m tscompress  msprime.trees
$ python3 -m tscompress -d msprime.trees.zarr 
$ ls -lh msprime*
-rw-r--r-- 1 jk jk 159K Apr 30 17:41 msprime.trees
-rw-r--r-- 1 jk jk 156K Apr 30 17:27 msprime.trees.original
-rw-r--r-- 1 jk jk  14K Apr 30 17:41 msprime.trees.zarr
```

(The semantics aren't quite gzip-like here --- we should have removed the msprime.trees.zarr file without --keep)

## What's this for?

The idea is that we have a bespoke compression/decompression utility for .trees files, which does substantially better than just gzipping the files because (a) we can use per-column codecs and filters from [numcodecs](https://numcodecs.readthedocs.io/en/latest/) and [zarr](https://zarr.readthedocs.io/en/latest/); and (b) we can do clever things to reduce space depending on how lossless we want to be. The current code is lossless WRT to the genotypes, but throws away a lot of information about the topology. We can add a bunch of options here to control this behaviour.

This is useful: tree sequences are small, but the space still adds up. We get very good results for real data out of tsinfer:
```
-rw-r--r-- 1 jk jk 297M Apr 30 17:35 1kg_chr20.trees
-rw-r--r-- 1 jk jk  43M Apr 30 17:36 1kg_chr20.trees.zarr
```

## Why isn't this in tskit?

Including compression codecs in tskit is tricky. Firstly, it would require us to take on some external dependencies: zlib at a minimum, but we'd probably want to have Zstandard or something to get modern numerical codecs. C level dependencies are hard, and it would significantly reduce the embeddability of the tskit C library. Secondly, we'd have to code this stuff up in C, which would be a *lot* harder and take a lot of time (and, as a consequence, probably not get done).

This seems like a good compromise: we have a lightweight, speed optimised file format built into tskit for computation, and a space-optimised file-format here.

## Why follow gzip semantics?

It seems like a logical thing to do, and makes it easy to define the interface. This might not be the perfect choice though, so I'm open to ideas here.

### CODE REVIEW

**Comment by molpopgen** [comment]
> The current code is lossless WRT to the genotypes, but throws away a lot of information about the topology.

Curious about the implications of this?

If I understand right: this is something you'd run after dumping the table collection to a file from tskit?  In Python, you'd `import tscompress` and have it as a second line of a `with` block or somesuch idea?

**Comment by agladstein** [comment]
I like it! And seems to potentially get at the space issue I've grappled with .trees files (https://github.com/tskit-dev/msprime/issues/730).

**Comment by petrelharp** [comment]
Very nice. I am also curious about the lossy compression?

**Comment by petrelharp** [comment]
Wow, that's very simple!  

Loss-wise, it just discards `node.time`? And, metadata?

**Comment by jeromekelleher** [comment]
I should have been clearer about the lossy-vs-lossless thing here. The current code is the result of an experiment to see how small I could make the files and *just* maintain the genotypes. This won't be the default behaviour, but some variant of if is still probably useful. The default behaviour would be completely lossless compression of everything, with byte-wise identical round-tripping. I'll code this up today and see what the compression we get is.

**Comment by hyanwong** [comment]
> ```
> -rw-r--r-- 1 jk jk 159K Apr 30 17:41 msprime.trees
> -rw-r--r-- 1 jk jk 156K Apr 30 17:27 msprime.trees.original
> -rw-r--r-- 1 jk jk  14K Apr 30 17:41 msprime.trees.zarr
> ```

Out of interest, why is the uncompressed file larger than the original? Also, isn't it a bit inconsistent to remove the original during compression, but keep it during decompression (if that's what's going on in the example)?

**Comment by jeromekelleher** [comment]
> If I understand right: this is something you'd run after dumping the table collection to a file from tskit? In Python, you'd import tscompress and have it as a second line of a with block or somesuch idea?

In Python you'd just have

```python
ts = msprime.simulate() # or whatever
tscompress.compress(ts, "compressed.trees.zarr")
```
to decompress:
```python
ts = tscompress.decompress("compressed.trees.zarr")
```

**Comment by jeromekelleher** [comment]
> Out of interest, why is the uncompressed file larger than the original? Also, isn't it a bit inconsistent to remove the original during compression, but keep it during decompression (if that's what's going on in the example)?

Good question, I didn't spot that! The semantics aren't correct right now, but the plan would be to just copy gzip semantics as closely as possible.

**Comment by jeromekelleher** [comment]
OK, nobody thinks this is a terrible idea in principle so I'm going to merge this much and plough ahead with the lossless version.

**Pull request merged**
